jobs:
- deployment:
  displayName: Deploy to kube.netricity.nl
  pool:
    vmImage: ubuntu-latest
  environment: kubernetes
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: KubernetesManifest@0
          displayName: Deploy
          inputs:
            action: deploy
            namespace: default
            manifests: manifests/deployment.yml|manifests/service.yml
            containers: 2atdev.azurecr.io/azp:latest
            imagePullSecrets: acr

