jobs:
- deployment:
  displayName: Deploy to kube.netricity.nl
  pool:
    vmImage: ubuntu-latest
  environment: kubernetes
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: KubernetesManifest@0
          displayName: Deploy
          inputs:
            kubernetesServiceConnection: kube-netricity-nl
            action: deploy
            namespace: default
            manifests: manifests/azagent.yaml
            containers: 2atdev.azurecr.io/azp:latest
            imagePullSecrets: acr

